# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: hIYh47@H&%67

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: 0Px$$2W%yt&Q
    salt: SyoRi0Z*Z361b5Jw

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  hellabueno.com:
    env:
      db_password: e0d1IzN*k899w
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "+o(nD{4KM-VXH+FWWH8M2qP7?YnURH3H(T*Gy>,.?Dd?M7x1j3AZ9|o`#zsiDBc`"
      secure_auth_key: "C!gEQxE1#q>i;CHq^APDxT_>@8x7+4j/2DDAUM)(8,a$QlM&`*R^QhM:E5n42n.="
      logged_in_key: "Ra,+_A;`fuP&$x`PrTW=vs{TOz.KDC-BX)$+;A7uspb*?TC|X3z}Y}`}W`bWre2["
      nonce_key: "7xUrw0!g#Y.}m@@z@J)2Su,Ukb9k$t2QH_cf!rg3Rd7{BWVCY3=vS4{[wa:QwE)l"
      auth_salt: "oN;Wqy}Q/F8t,n$-JxN0?$%4FXQ$GxB,I8%=`1:@`4q({&j*;3/r<2E*r(D[V_su"
      secure_auth_salt: "Ogf2?T+;oG%K[vtn{+#ui6%oMYSHl#7G3G6>{EBUV@uGL2/y,+3<$+$p]Pa|&g{8"
      logged_in_salt: "C3E9u/$)_AoRinGJifcY1gBv{$4j7|X^e&jz6o]x4J7qQ3yiW49Df`@&eW]Jt{Fi"
      nonce_salt: "yppVy0Z4qgd6#<6maq*Tq@jdC!@m<yo|/B?;I3yXS.)ni.,3zr0+7W?j)+BP+e$P"
